addr: 0.0.0.0:5353
protocol: tcp
dns:
  - 8.8.8.8
  - 8.8.4.4
overrides:
  - domain: google.com
    ip: 8.8.8.8
  - domain: "*.test.uk"
    ip: 127.0.0.1
  - domain: "*.aaa.test.abc"
    ip: 127.0.0.1
  - domain: test.com
    ip: 127.0.0.1
  - domain: cccc.com
    ip: 127.0.0.1
  - domain: zzzz.com
    ip: 127.0.0.1
