addr: "0.0.0.0:5355"
network: "udp"
cache_ttl: 14400
log_file: ""
dns:
  - addr: "8.8.8.8:53"
    network: "tcp"
  - addr: "8.8.4.4:53"
    network: "udp"
hosts:
  - host: google.com
    ip: 127.0.1.1
  - host: "test.com"
    ip: 127.0.0.1
  - host: "*.test.com"
    ip: 127.0.0.1
