addr: "0.0.0.0:5355"
network: "udp"
cache_ttl: 14400
debug: true
dns:
  - addr: "8.8.8.8:53"
    network: "tcp"
  - addr: "8.8.4.4:53"
    network: "udp"
hosts:
  - domain: google.com
    ip: 127.0.1.1
  - domain: "test.com"
    ip: 127.0.0.1
  - domain: "*.test.com"
    ip: 127.0.0.1
