addr: 0.0.0.0:5355
protocol: udp
debug: true
dns:
  - 8.8.8.8
  - 8.8.4.4
overrides:
  - domain: google.com
    ip: 127.0.1.1
  - domain: "test.com"
    ip: 127.0.0.1
  - domain: "*.test.com"
    ip: 127.0.0.1
